### ISSUE TITLE
Naming - DynamoDb -> DynamoDB

### ISSUE THREAD

**Issue by damianh** [AllocZero/EfficientDynamoDb#105]
Spotted this difference and can't unsee :)

In AWSSDK, `DynamoDB` with a captial `B` is used in all types, namespaces, docs etc. To be consistent, consider following the vendor's naming.

**Comment by lezzi** [comment]
This is a slightly controversial topic and we had a lot of discussions internally with @firenero. 

One of the reasons we don't like using uppercase `DB` is because it generates 3 subsequent uppercase characters which makes it harder to read/type. For example `DynamoDBProperty` or `DynamoDBContext`.

The rule we want to follow is to be consistent within the EfficientDynamoDb library. We don't want to limit ourselves to naming / technical decisions made in the SDK itself.

It would be interesting to wait a bit and collect more feedback regarding the naming, as we still can change this before 1.0 is released.

**Comment by damianh** [comment]
Fair enough and it's definitely a bit bike-sheddy. If I have both AWSSDK.DynamoDB2 and this package reference in the same project, one will have to deal with the mixed casing of the name.

**Comment by MarkPflug** [comment]
I would definitely stick with "Db", as it matches the majority of examples in the BCL, e.g. `DbConnection`, `DbDataReader`, etc. Yes, there is the `DBNull` as a counterexample, but it is an exception that I suspect they'd probably change if they could.

**Comment by damianh** [comment]
Would just like to say, this is not a hill I would die one :)

**Comment by firenero** [comment]
@damianh It's a controversial topic indeed. I guess it's more like a personal taste than a real difference. I agree with @lezzi that 3 sequential uppercase characters are harder to read/write.

> If I have both AWSSDK.DynamoDB2 and this package reference in the same project, one will have to deal with the mixed casing of the name.

It's a tradeoff we had to make. On the other hand, if we keep naming the same, one will have to deal with different imports and it would be impossible to know what library is used just by looking at attributes. You would have to check imports all the time.

**Comment by damianh** [comment]
As I said, not a hill ;)

Close as discision made.

**Comment by damianh** [comment]
Some feedback from the wild:
- "The case difference between `DynamoDbProperty` vs `DynamoDBProperty` is "annoying" due to impact & readability on code base."
- "Be either a drop-in replacement, or give it an explicit name such as `EfficientDynamoDBProperty` and not rely on subtle case difference".
