### ISSUE TITLE
Transact.PutItem issue

### ISSUE THREAD

**Issue by briananderton-il** [AllocZero/EfficientDynamoDb#127]
Transact.PutItem seems to be ignoring the entity passed in, causing a ValidationError when the transaction is sent because of a null value.   I'm guessing you want to be creating an ItemNode here?  I'd write up a PR but not sure where to get a reference to the DynamoDbContext to get the entity ClassInfo needed.

**Comment by lezzi** [comment]
Thank you for reporting the bug.

Yeah, the node is missing. We can't use the `ItemNode` because as you mentioned we don't have access to the `DynamoDbContext`. I think we need to create a new node type that will contain a `Type` property instead of `DdbClassInfo`. Then inside `WritePutItem` we can use the type property to retrieve the `DdbClassInfo`.

If you want to contribute feel free to create the PR, or I will have time to hotfix this tomorrow evening.

**Comment by lezzi** [comment]
@briananderton-il, the fix is available in the `0.9.3-alpha.0.2`

**Comment by briananderton-il** [comment]
Thanks!  Looks good.
