### ISSUE TITLE
support execute-statement for 'Partiql'

### ISSUE THREAD

**Issue by Newp** [AllocZero/EfficientDynamoDb#173]
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-reference.select.html

The aws partiql grammar is also supported on the aws dynamodb console page, and the sql grammar makes it easy to use dynamodb agent. However, aws-sdk is a natural problem with AttributeValue and has high memory allocation and slow processing speed. I wonder if you have any plans to support this.

Thank you.

**Comment by Newp** [comment]
https://github.com/AllocZero/EfficientDynamoDb/pull/174/files#diff-c8a3d5a6f3a559226e0df63b934bd3b093fc879f55c530c77c39d4313686ef68R20-R35

There may be inconvenient contents because you can't speak English and use a translator.

Dynamodb has a context-based design and a request message-based design. Because partiql is basically based on request message, it was very difficult to add to the current DbContext-based code. For example, partiql finds a table based on the query status of the message, but the context-based design was already considered difficult to handle in the same class from this part because the context-based design requires a table name to be specified in advance in the context config.

I haven't worked for a long time yet, so I haven't deserialized json as a general object, but I'd like to suggest a basic concept.

I would appreciate it if you could let me know if you are willing to reflect the functions of this concept.

**Comment by lezzi** [comment]
EficientDynamoDb always provides a low-level implementation (request message-based design) which usually returns a response containing a document (map of attribute values, the memory allocation cost here is much less than official SDK because attribute struct is much smaller).

There is also a way to map response directly into classes to skip the attributes allocations. So technically low-level approach can be implemented to cover most use cases with one main disadvantage - PartiQL statement has to be passed as string and all params have to be passed as attribute values.

We have not decided yet if it is worth implementing right now since our focus was on releasing the v1 stable version first.
