### ISSUE TITLE
Proposal to introduce xunit.

### ISSUE THREAD

**Issue by Newp** [AllocZero/EfficientDynamoDb#176]
I used the translator.

Personally, I think the biggest intersection of NUnit/xUnit is support for async/await.
The market share has changed since five to six years ago when async/await was in full swing. While xUnit has good async/await support, I remember that NUnit was very uncomfortable at the time (.whether the context was locked by walking Result).

**Comment by firenero** [comment]
NUnit works perfectly fine with async/await. We used it for the last several years without any noticeable issues. Starting this project we had a discussion with @lezzi about the test framework because they are all pretty similar. However, NUnit has much better [documentation](https://docs.nunit.org/articles/nunit/intro.html) while xUnit documentation is [extremely poor](https://xunit.net/#documentation). Since there are no other real differences, we decided to stick to NUnit this time.
