### ISSUE TITLE
Optimistic concurrency using native EfficientDynamoDb API

### ISSUE THREAD

**Issue by OleksiiBalanenko** [AllocZero/EfficientDynamoDb#177]
Hi, developers.
There is a question related to optimistic concurrency using EfficientDynamoDb API. 
In the documentation I found DynamoDbVersion attribute support (which enables optimistic concurrency by default), but you do not recommend to use Compatibility APIs like SaveAsync and DeleteAsync.
We are using DeleteItem, PutItem and UpdateItem APIs and want to have concurrency check.

Please, advise if there is a way to have something like "DynamoDbVersion" behavior.
Perhaps, Conditional checks could facilitate the issue, but looks like it requires additional complexity in my logic.

Hope for your support,
Thanks.

**Comment by firenero** [comment]
Hi @OleksiiBalanenko.

Conditional checks are the way for implementing optimistic concurrency for `DeleteItem`, `PutItem`, and `UpdateItem` yourself. We decided not to add any simpler way to do it yet because generic optimistic concurrency doesn't align well with the flexibility of these operations via custom conditions. Nevertheless, we're open to discussing API proposals in this area so feel free to share if you have any.

If you don't care about having a full object to perform `SaveAsync ` and `DeleteAsync`, it's ok to use them. These methods are not recommended because for the majority of DDB operations you don't really need to change the full object. But you have to reload data from DB in case of concurrency error despite updating data that could have been updated concurrently without errors with more granular conditions.

**Comment by OleksiiBalanenko** [comment]
Hi @firenero,
Thanks for your answer. It was helpful.
