### ISSUE TITLE
Support default name of property

### ISSUE THREAD

**Issue by Newp** [AllocZero/EfficientDynamoDb#180]
The name must be initialized in the DynamoDbPropertyAttribute. When the naming convention is the same as the class's name, these codes create unnecessary tasks and create an environment where mistakes can occur.

If the name is not specified separately as shown below, it would be nice if it was automatically set to PropertyInfo/FieldInfo.Name.

[DynamoDbProperty]
public string TextValue {get; set;}

The code above has the following effects.
[DynamoDbProperty(**nameof(TextValue)**]
public string TextValue {get; set;}

**Comment by firenero** [comment]
Hi @Newp 
We had a discussion about it some time ago with @lezzi and decided not to use field/property name as a default DDB attribute name. It's a potentially dangerous practice to do so because of the following reasons:

1. Renaming a property will impact your DDB attribute name and likely cause bugs.
1. RCU and WCU consumption depends on item size that includes not only data but attribute name. Property names in C# tend to be verbose, thus needlessly increasing your DDB total cost of ownership.

Looking at these issues, we'd like to encourage safer and cheaper design choices. But if you 100% want to name your DDB names to match C# names, you're free to use your `nameof` approach.
