### ISSUE TITLE
Generics do not play well with "Condition" while querying

### ISSUE THREAD

**Issue by wjax** [AllocZero/EfficientDynamoDb#184]
We have been creating IRepository<T> interfaces in order to use DynamoDb with EfficientDynamoDb library.

The thing is that we would like to "hide" EfficientDynamo behind an Interface for mocking or future change. While creating several methods, we have faced a problem on how to implement query conditions on generics.
It can be lack of knowledge on my side, that's why I am asking :)

Imagine an IDynamoDbRepository with the following method declaration:
```
public interface IDynamoDbRepository<T> 
{
    Task<IReadOnlyList<T>> GetAllByPK(string pkValue, string pkName = "PK");
}
```

The implementation would be:
```
public async Task<IReadOnlyList<T>> GetAllByPK(string pkValue, string pkName = "PK")
{
    var condition = Condition<T>.On(XXXXX).EqualTo(pkValue);
    return await _dynamoDbContext.Query<T>()
                .WithKeyExpression(condition)
                .ToListAsync();
}
```

The problem is the __XXXXX__. 
As we do not know the type, we cannot construct the condition that in a known class would be:
```
var condition = Condition<InterfaceDefinition>.On(x => x.PK).EqualTo(pkValue);
```

It surely could be fixed by using reflection, but I wanted to ask if there is any other cleaner (and more GC friendly) way of doing this.

Thanks

**Comment by firenero** [comment]
There are several possible solutions/workarounds for this case.

## Mocking

It only addresses half of your reasoning to hide behind an interface but I have to mention first that EfficientDynamoDb calls are mockable by design. You don't have to hide them behind the interface to be able to unit test your DB access code. It may or may not affect your decision to abstract away but if it does, removing the repository layer altogether will be the easiest way to solve your issue. You can find an example of such mocking [here](https://github.com/AllocZero/EfficientDynamoDb/blob/7c11aa8cc105848a9b3e3a9125b080815f9f6c45/EfficientDynamoDb.Tests/Examples/DynamoDbContextExampleTests.cs#L13-L27).

## Generic constraints

You can add an interface to all your entity classes that will provide a contract for PK/SK. Then you add your interface as a constraint to the generic repository method.

```csharp
public interface IDynamoDbEntity
{
    public string Pk { get; } 
    
    public string Sk { get; }
}

public class SomeEntity : IDynamoDbEntity
{
    [DynamoDbProperty("pk", DynamoDbAttributeType.PartitionKey)]
    public string Pk { get; }
    
    [DynamoDbProperty("sk", DynamoDbAttributeType.SortKey)]
    public string Sk { get; }
}

public interface IDynamoDbRepository<T> 
{
    Task<IReadOnlyList<T>> GetAllByPkAsync(string pkValue);
}

public class DynamoDbRepository<T> : IDynamoDbRepository<T> where T: class, IDynamoDbEntity
{
    private readonly IDynamoDbContext _dynamoDbContext;

    public Task<IReadOnlyList<T>> GetAllByPkAsync(string pkValue)
    {
        var condition = Condition<T>.On(x => x.Pk).EqualTo(pkValue);
        return _dynamoDbContext.Query<T>()
            .WithKeyExpression(condition)
            .ToListAsync();
    }
}
```

Then the call will look like this:

```csharp
var repo = new DynamoDbRepository<SomeEntity>();
var result = repo.GetAllByPKAsync("testPk");
```

If you want, you can make the interface generic at the cost of a bit more ugly call like this:

```csharp
public interface IDynamoDbEntity<out TPk, out TSk>
{
    public TPk Pk { get; } 
    
    public TSk Sk { get; }
}

public class SomeEntity : IDynamoDbEntity<string, string>
{
    [DynamoDbProperty("pk", DynamoDbAttributeType.PartitionKey)]
    public string Pk { get; }
    
    [DynamoDbProperty("sk", DynamoDbAttributeType.SortKey)]
    public string Sk { get; }
}

public interface IDynamoDbRepository<T, in TPk, in TSk> where T: IDynamoDbEntity<TPk, TSk>
{
    Task<IReadOnlyList<T>> GetAllByPkAsync(TPk pkValue);
}

public class DynamoDbRepository<T, TPk, TSk> : IDynamoDbRepository<T, TPk, TSk> 
    where T : class, IDynamoDbEntity<TPk, TSk>
{
    private readonly IDynamoDbContext _dynamoDbContext;
    
    public Task<IReadOnlyList<T>> GetAllByPkAsync(TPk pkValue)
    {
        var condition = Condition<T>.On(x => x.Pk).EqualTo(pkValue);
        
        return _dynamoDbContext.Query<T>()
            .WithKeyExpression(condition)
            .ToListAsync();
    }
}
```

In this case the call will look like this:

```csharp
var repo = new DynamoDbRepository<SomeEntity, string, string>();
var result = repo.GetAllByPKAsync("testPk");
```

**Comment by wjax** [comment]
Hi Mykhailo,

Many thanks for the answer. And sorry for the question as I had it in front of my eyes but couldn't see it. I had already created the IDynamoDBItem but I was lacking the constraint in the type of T.

Keep the good work
