### ISSUE TITLE
Wondering if there are any examples using this in single table design 

### ISSUE THREAD

**Issue by TheBreadGuy** [AllocZero/EfficientDynamoDb#208]
currently been playing around with https://github.com/abelperezok/DynamoDB-BaseRepository/tree/master but has few limiting factors. 

planning on trying to rebuild something similar using EfficientDyn. though I'm not to experienced.

**Comment by firenero** [comment]
Hi @TheBreadGuy,

There are multiple ways to access data in a single table design. If you're asking about retrieving different types of data in a single query, you need to use document returns and then parse the data based on your conditions. There is an [example in docs](https://alloczero.github.io/EfficientDynamoDb/docs/dev_guide/dev-guide/high-level/read#document-returns).

Also, a slightly [different example](https://github.com/AllocZero/EfficientDynamoDb/issues/205#issuecomment-1542648147) is available in another recent discussion.

**Comment by TheBreadGuy** [comment]
ty for reply.

sorry should've said more details. was thinking about high level classes on best way to add prefix for table. 

Would it be safe to add property like [DynamoDbPrefix("Event")] or Could it even be possible to do something like  [DynamoDbUsePrefix] and would just use class name.

At moment looking at converters but as can only pass type as far as know. each class would need it own.

**Comment by firenero** [comment]
Such attributes are not something that I'd want to add as they hide necessary functionality behind some magic. 

Converters are a way to go to achieve what you want. My suggested solution would be to create a generic wrapper for your keys and then add a converter to it. The wrapper could look similar to this:
```csharp
public class KeyWrapper<T> 
{
    public string Prefix { get; set; }
    public T Value { get; set; }
    public override string ToString() => $"{Prefix}{Value.ToString()}";
}
```

Then the converter could be similar to this:
```csharp
public sealed class KeyWrapperConverter<T> : DdbConverter<KeyWrapper<T>>
{
    public override KeyWrapper<T> Read(in AttributeValue attributeValue)
    {
        // Parse attribute value and return KeyWrapper<T> instance.
    }

    public override AttributeValue Write(ref KeyWrapper<T> value)
    {
        return new StringAttributeValue(value.ToString());
    }
}
```

Then you can apply this converter to your property like this:
```csharp
[DynamoDbProperty("pk", typeof(KeyWrapperConverter<int>), DynamoDbAttributeType.PartitionKey)
public KeyWrapper<int> PartitionKey { get; set; }
```

Instead of applying converter to every wrapper property, you can use [ConverterFactory](https://alloczero.github.io/EfficientDynamoDb/docs/dev_guide/dev-guide/high-level/converters/#for-a-context) and register it for DynamoDbContext to make it applied automatically.

**Comment by TheBreadGuy** [comment]
thank you trying that approach now.

Also, I understand not wanting to hide  necessary functionality. Would it be idea to say add third level say 'Maintained High Level' with such options?

Wondering how everyone else solves single table without repeating prefix everywhere. 

Though was unsure of keywrapper, it does have advantage splitting the key from prefix. will test more with it

**Comment by firenero** [comment]
There are additional problems with attribute-based prefixes beyond making the functionality less visible. Here are a couple of them:

1. Prefix attributes can cause conflicts with converters. If a prefix attribute and a converter are both used at once, it may be unclear whether the converter modifies just the value or both the value and prefix. This problem is even more difficult to spot if converters are being used at the context level. 
2. Prefix attributes are only compatible with the `String` DDB type. If your DDB key is of a different type, like `Number`, then prefix attributes won't work. 

Furthermore, using prefix attributes could potentially affect performance. We can't be sure without a thorough investigation. Given the simple alternative – using just one class and one converter – I'm wary of introducing attributes that could create more problems than benefits.

**Comment by TheBreadGuy** [comment]
Have been using using keywrapper approach and have to agree will be less problematic then attribute would've been. with more control.

Modified it slightly. and to use Generics. 

Disclaimer: this not perfect code. or best practice's. and may contain things you should never do. but here is what I've done.

```
[JsonIgnore]
        [DynamoDbProperty("pk", typeof(PKWrapperConverter<string>), DynamoDbAttributeType.PartitionKey)]
        public PKWrapper<string> PartitionKey { get; set; } = new PKWrapper<string> { Prefix = "PERSON", Value = "" };

        [JsonIgnore]
        [DynamoDbProperty("sk", typeof(SKExtraWrapperConverter<string>), DynamoDbAttributeType.SortKey)]
        public SKExtraWrapper<string> SortKey { get; set; } = new SKExtraWrapper<string> { PrefixGroup = "PERSON", Prefix = "STATS" , Value = "", ValueGroup = "" };

        IPartitionKey IDynamoDbEntity<string>.PartitionKey
        {
            get => PartitionKey;
            set => PartitionKey = (PKWrapper<string>)value;
        }

        ISortKey IDynamoDbEntity<string>.SortKey
        {
            get => SortKey;
            set => SortKey = (SKExtraWrapper<string>)value;
        }

        [DynamoDbProperty("UUID")]
        public string UUID
        {
            get => _UUID;
            set
            {
                _UUID = value;
                SortKey.Value = value;
            }
        }
```


Does duplicate few things but allows me not to worry about key formatting.

**Comment by firenero** [comment]
Glad it worked for you @TheBreadGuy. I'm closing this issue but feel free to re-open it if you have more questions.
