### ISSUE TITLE
Why does EmitMemberAccessor.CreateConstructor(Type) require a public constructor?

### ISSUE THREAD

**Issue by bill-poole** [AllocZero/EfficientDynamoDb#229]
It seems that entity objects I read/write from/to DynamoDB need to have a public constructor, otherwise `EmitMemberAccessor.CreateConstructor(Type)` returns null and the `DdbClassInfo` constructor throws an `InvalidOperationException`. Is there a reason for this limitation? Or could the limitation be removed to support non-public constructors?

**Comment by firenero** [comment]
If I remember correctly, there were issues with deserializing DDB response to objects if there is no parameterless constructor. I would like to add support for other constructor types but I need to evaluate how much work is required for it.

**Comment by bill-poole** [comment]
I agree that there needs to be a parameterless constructor. The limitation is that the parameterless constructor must be public. I think the issue is line 19 in EmitMemberAccessor.cs shown below.

```csharp
ConstructorInfo? realMethod = type.GetConstructor(BindingFlags.Public | BindingFlags.Instance, binder: null, Type.EmptyTypes, modifiers: null);
```

The binding flags are `BindingFlags.Public | BindingFlags.Instance` - i.e., `BindingFlags.NonPublic` is missing.

If `BindingFlags.NonPublic` were to be added, then it should be possible to have a non-public parameterless constructor.

**Comment by firenero** [comment]
I think some limitations prevented us from supporting non-public constructors but I don't remember what was that exactly. I will check again later this week and post my findings. If it's indeed possible to support non-public constructors I'm up to removing this limitation.

**Comment by bill-poole** [comment]
Thanks @firenero.

**Comment by firenero** [comment]
@bill-poole public constructors are required now because objects are created using the IL Emit in `EmitMemberAccessor.CreateConstructor(Type)` as below:
```csharp
generator.Emit(OpCodes.Newobj, realMethod);
```
It only works for public constructors. Fallbacking to reflection in case of private constructors is not that trivial because sometimes the type without a public constructor can be a generic argument of `Type` parameter. So far I'm not convinced that adding support for non-public constructors is worth the effort because usually you can add a public constructor. 

Can you tell something about your use case and why non-public constructors are important there?

**Comment by bill-poole** [comment]
I have objects that I'm saving to DynamoDB that have certain invariants that the object enforces - i.e., its properties can't just have any value. However, when loading an object from the database, we can trust that the data is correct - i.e., we don't need to worry about enforcing the invariants. If I have a public parameterless constructor, then I cannot guarantee that the invariants are enforced because an object can be created with no property values, and then I need to have public setters for all the properties, allowing any values to be set for the properties - i.e., bypassing all the invariants.

That's why ORMs tend to support creating entity objects with non-public parameterless constructors.

Note that EfficientDynamoDb seems to support setting property values using non-public setters. I just can't get EfficientDynamoDb to create the objects using a non-public parameterless constructor.

What do you mean by "sometimes the type without a public constructor can be a generic argument of Type parameter"?

It looks like some work was done in this space for .NET 8 (see [here](https://github.com/dotnet/runtime/issues/36194) and [here](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.constructorinfo?view=net-8.0)). Would `ConstructorInfo` meet your requirements and allow invoking non-public constructors?

**Comment by firenero** [comment]
> What do you mean by "sometimes the type without a public constructor can be a generic argument of Type parameter"?

Disregard that. I meant that the `EmitMemberAccessor.CreateConstructor(Type)` method is used to create not only user-provided types but also some internal wrappers required for the library to work, such as `GetItemEntityProjection<T>. However, it seems like this doesn't matter in this case.

I think we can indeed fallback to a reflection call in case there is only a private constructor. However, I need to do more tests to confirm it works for all possible cases and do some benchmarks to confirm that it doesn't hurt the optimal flow. However, keep in mind that if all goes well and this feature is added, it will have worse performance characteristics simply because reflection is much slower than IL emitting.

**Comment by bill-poole** [comment]
I tried adding `BindingFlags.NonPublic` at line 19 in EmitMemberAccessor.cs as shown below and the `CreateConstructor(Type)` method successfully returned a non-null `Func<object>` delegate to invoke a private parameterless constructor.

```csharp
ConstructorInfo? realMethod = type.GetConstructor(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance, binder: null, Type.EmptyTypes, modifiers: null);
```

Once the `CreateConstructor(Type)` method has created the constructor delegate for a type, the delegate is cached, so it shouldn't matter to the performance of invoking that delegate whether the constructor is public or private. However, just to make sure, I benchmarked both scenarios.

I also tested performance of invoking the constructor (public and private) using reflecting using the new `ConstructorInvoker` class added in .NET 8.

The benchmark results are below.

| Method                     | Mean     | Error     | StdDev    |
|--------------------------- |---------:|----------:|----------:|
| Public_DynamicMethod       | 3.681 ns | 0.0793 ns | 0.0703 ns |
| Public_ConstructorInvoker  | 5.062 ns | 0.1021 ns | 0.0955 ns |
| Private_DynamicMethod      | 3.660 ns | 0.0759 ns | 0.0710 ns |
| Private_ConstructorInvoker | 5.137 ns | 0.0624 ns | 0.0553 ns |

**Comment by firenero** [comment]
Unfortunately, we can't use `ConstructorInvoker` because the library still targets `netstandard2.1` that doesn't have access to .NET 8 APIs. I've benchmarked `realMethod.Invoke()` approach and it's ~2 times slower than doing emit and slightly slower than `ConstructorInvoker`:

| Method     |     Mean |     Error |    StdDev | Ratio |
| ---------- | -------: | --------: | --------: | ----: |
| Reflection | 6.147 ns | 0.1245 ns | 0.1165 ns |  1.00 |
| Emit       | 3.417 ns | 0.0977 ns | 0.0960 ns |  0.56 |
| Invoker    | 5.140 ns | 0.0629 ns | 0.0589 ns |  0.84 |

Overall, I believe there is not much we can do about private constructors to narrow the gap so I think we can use the reflection for this case. It will take some time to implement and test the change but hopefully, I can get it done next week.

**Comment by bill-poole** [comment]
Can you help me understand why you can't use emit for private constructors (i.e., just update line 19 in EmitMemberAccessor like I proposed above)? It seems to work for private constructors in my testing and without the performance hit of using reflection.

**Comment by firenero** [comment]
Sorry, I've misread your previous message. Just tried it again and it indeed works. Probably I changed something else last time I tested and accidentally broke emitting. 

In that case, nothing stops us from adding this feature. I still want to test various cases but since it's a less dangerous change I think I will have time to do that by the end of the week.

**Comment by bill-poole** [comment]
That's great, thanks!
