### ISSUE TITLE
Questions/suggestions about the `CustomIntConverter` example in the documentation

### ISSUE THREAD

**Issue by bill-poole** [AllocZero/EfficientDynamoDb#230]
The [documentation](https://alloczero.github.io/EfficientDynamoDb/docs/dev-guide/high-level/converters) provides an example for a `CustomIntConverter`. In its current form, the example doesn't compile for the following reasons:
1. The `Read(ref DdbReader)` method accesses `reader.JsonReaderValue` (which is internal) to invoke `reader.JsonReaderValue.GetString()`. I believe this should actually be `reader.JsonReader.GetString()`.
2. The converter overrides `Write(ref T value)`, but `T` is not defined. I believe this should actually be `Write(ref int value)`.

After the above changes, the `Read(ref DdbReader)` method becomes:

```csharp
public override int Read(ref DdbReader reader)
{
    if (!Utf8Parser.TryParse(reader.JsonReader.ValueSpan, out int value, out _))
        throw new DdbException($"Couldn't parse int ddb value from '{reader.JsonReader.GetString()}'.");

    return value;
}
```

However, this reads from `reader.JsonReader.ValueSpan`, which assumes that
- the value is a contiguous `ValueSpan`, rather than a `ValueSequence`; and
- the value is not escaped.

Are these assumptions valid? i.e., are they guaranteed to always be valid? If not, then I believe the example should be updated to something like:

```csharp
public override int Read(ref DdbReader reader)
{
    scoped ReadOnlySpan<byte> utf8Text;
    var jsonReader = reader.JsonReader;
    if (jsonReader.HasValueSequence || jsonReader.ValueIsEscaped)
    {
        var length = jsonReader.HasValueSequence
            ? (int)jsonReader.ValueSequence.Length
            : jsonReader.ValueSpan.Length;
	if (length > MaxDynamoDbNumberAttributeValueLength)
	{
            throw new DdbException("DynamoDB number string too long");
	}

        Span<byte> buffer = stackalloc byte[length];
        utf8Text = buffer[..jsonReader.CopyString(buffer)];
    }
    else
    {
        utf8Text = jsonReader.ValueSpan;
    }

    return int.Parse(utf8Text);
}
```

**Comment by firenero** [comment]
Thanks for pointing out compilation errors. If you want you can create a PR with these fixes I will merge it ASAP. It's ok if you don't want to - in this case, I will update the docs myself on the weekend. 

The assumptions you've mentioned are guaranteed to be valid: 
- `byte[]` is used for JSON buffer so the `JsonReader` will always use `ValueSpan`. According to the [Utf8JsonReader guide](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/use-utf8jsonreader#read-with-multi-segment-readonlysequence), the `ValueSequence` can only be used if the JSON source is `ReadOnlySequence<byte>` that doesn't happen in our case.
- DynamoDB always returns numbers without escaping so we're not concerned about it. That said, you could serialize `int` as a custom string with escaping so you would need to unescape it. But we can't cover all possible cases in a single example so I'd prefer it simple and more applicable to a "common" use case.
- `length > MaxDynamoDbNumberAttributeValueLength` - this condition seems to be redundant because the Number attribute in DynamoDB can hold up to 38 significant digits which is way more than a 32-bit integer can handle anyway. 

Of course, you can handle all possible cases of `jsonReader.ValueIsEscaped`, `jsonReader.HasValueSequence`, and data length in your converter if you want to be extra safe. We don't do it for library converters because we try not to waste CPU cycles when it's possible. And sometimes extra comparison can make a noticeable change in performance due to CPU branch prediction misses.

**Comment by bill-poole** [comment]
Thanks @firenero. Can I suggest updating the documentation to explicitly state that `HasValueSequence` is guaranteed to always be false, so the value can always be read from `ValueSpan` (unless there is escaping, which as you say only happens if the converter writes escaped strings, in which case that's an internal matter for the converter).

i.e., that's important information for a developer using this library to have, so they know they don't need to worry about `HasValueSequence`/`ValueSequence`. That is, I now know that if `HasValueSequence` is true, then this represents an error condition and it's okay for my converter to throw an exception rather than having to deal with the scenario.

> length > MaxDynamoDbNumberAttributeValueLength - this condition seems to be redundant because the Number attribute in DynamoDB can hold up to 38 significant digits which is way more than a 32-bit integer can handle anyway.

Yes good point - although it's important that the buffer be longer than the 20 maximum possible characters for a signed 64-bit number so that an overflow would actually cause an exception to be thrown. But given `HasValueSequence` and `ValueIsEscaped` are guaranteed to be false, I don't need to copy into a buffer anyway, so it doesn't matter anyway.

I put the check there to put an upper bound on the size of the buffer - i.e., just in case DynamoDB misbehaved and returned a number string vastly longer than the maximum documented/specified length of 38 characters.

**Comment by firenero** [comment]
@bill-poole I've fixed the compilation errors in the example and added a note that `ValueSpan` can always be used to the following [JSON reading](https://alloczero.github.io/EfficientDynamoDb/docs/dev-guide/high-level/converters#json-reading) section.

Please let me know if it looks good and we can close this issue, or if there is anything else to add.

**Comment by bill-poole** [comment]
Thanks @firenero. That change looks good thanks.

Can I also suggest clarifying "The DdbReader.JsonReader.Read method should not be explicitly called unless you are writing a converter for a non-primitive JSON type like an object or array" to:

The DdbReader.JsonReader.Read method should not be explicitly called unless you are writing a converter for a non-primitive DynamoDB attribute type - i.e., a map, list or set.

"JSON type like an object or array" could be misunderstood to mean if you are reading/writing an arbitrary JSON-serializable .NET object (like an object or an array), which must of course be read/written as a string (or binary) attribute, not as raw JSON.

**Comment by firenero** [comment]
Thanks for the suggestion, updated the doc. 

I think it makes sense to close this issue since the original issue was addressed. Thanks again for your contribution @bill-poole and feel free to create a new issue if you find other things we can improve in docs.

**Comment by bill-poole** [comment]
Thanks @firenero!
